In [111]:
import pandas as pd
import numpy as np
import cv2
import uuid

In [103]:
%load_ext autoreload
%autoreload 2
from gensim import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [104]:
env = Enviroment.Enviroment(100, 100, 100, 3, 3)

Creature a66bf25a neuron array:
[[ 0.          0.          9.         10.          1.94994706]
 [ 1.          0.         12.          9.          3.27243613]
 [ 1.          1.          8.          3.         -4.09459763]]
Creature eb0707c6 neuron array:
[[ 0.          1.          0.          3.          2.59010798]
 [ 1.          1.         11.          1.         -2.12014697]
 [ 0.          0.          4.         10.         -4.07289549]]
Creature 48d43da0 neuron array:
[[ 1.          0.         10.          9.          2.052082  ]
 [ 1.          1.         13.          5.          3.78696384]
 [ 1.          1.         10.          5.         -2.30549475]]
Creature 0bb30512 neuron array:
[[ 0.          1.         14.          6.         -4.06040197]
 [ 0.          1.          2.          7.          0.82891243]
 [ 0.          1.          1.          6.          1.04475704]]
Creature 90316047 neuron array:
[[ 0.          0.          7.          8.         -1.20053459]
 [ 0.          1.

In [105]:
cr_arr = env.creature_array

In [106]:
cr_arr[0].neuron_array[1]

array([ 1.        ,  0.        , 12.        ,  9.        ,  3.27243613])

In [109]:
cr_arr[0].gene_array[0].get_gene_hash()

'ac4cde'

AttributeError: module 'cv2' has no attribute 'RGB'

In [118]:
def hex_to_rgb(value):
    """Return (red, green, blue) for the color given as #rrggbb."""
    value = value.lstrip('#')
    lv = len(value)
    return [(int(value[i:i + lv // 3], 16) for i in range(0, lv, lv // 3))]

In [119]:
hex_to_rgb(cr_arr[0].gene_array[0].get_gene_hash())

array(<generator object hex_to_rgb.<locals>.<genexpr> at 0x150c91eb0>,
      dtype=object)